---
- name: ensure gems are installed
  command: "{{ rails_deploy_bundle }} install --deployment --path={{ rails_deploy_bundle_path }} --without={{ rails_deploy_bundle_without|join(',') }} chdir={{ rails_deploy_path }}"
  become: true
  become_user: "{{ rails_deploy_user }}"

- name: ensure database is migrated
  shell: ". /etc/default/{{ rails_deploy_app_name }} && {{ rails_deploy_bundle }} exec rake db:migrate chdir={{ rails_deploy_path }}"
  when: inventory_hostname == rails_deploy_migrate_master_host and rails_deploy_migrate
  register: migrate_output
  become: true
  become_user: "{{ rails_deploy_user }}"

- name: show migration output
  debug: var=migrate_output.stdout_lines
  when: migrate_output.stdout_lines is defined

- name: ensure rails_repo_status_changed fact is set
  set_fact: rails_repo_status_changed="{{ repo_status.changed }}"

- name: ensure database is seeded
  shell: ". /etc/default/{{ rails_deploy_app_name }} && {{ rails_deploy_bundle }} exec rake db:seed chdir={{ rails_deploy_path }}"
  when: inventory_hostname == rails_deploy_migrate_master_host
  become: true
  become_user: "{{ rails_deploy_user }}"

- name: ensure assets are precompiled
  shell: ". /etc/default/{{ rails_deploy_app_name }} && {{ rails_deploy_bundle }} exec rake assets:precompile chdir={{ rails_deploy_path }}"
  when: rails_deploy_precompile_assets
  become: true
  become_user: "{{ rails_deploy_user }}"
